version: 2.1

executors:
  standard:
    docker:
      - image: cimg/base:2021.05

jobs:
  check-code-format:
    executor: standard
    steps:
      - run:
          name: No-op for check-code-format
          command: echo "Skipping code format check (no-op)"

  build:
    executor: standard
    steps:
      - run:
          name: No-op for build
          command: echo "Skipping build (no-op)"

  check-memory-leaks:
    executor: standard
    steps:
      - run:
          name: No-op for check-memory-leaks
          command: echo "Skipping memory leak check (no-op)"

workflows:
  main:
    jobs:
      - check-code-format
      - build:
          requires:
            - check-code-format
      - check-memory-leaks:
          requires:
            - build

