version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: git submodule update
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install build-essential automake autoconf libtool patchelf
      - run:
          name: Build project
          command: |
            make

workflows:
  main:
    jobs:
      - build